version: '3'
 
services:
  db:
    image: mariadb:11.2
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      - backend
 
  web:
    image: nginx:1.27.1-alpine3.20
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - wp-content:/var/www/html #wp-content
      - /etc/localtime:/etc/localtime
    depends_on:
      - wordpress
    restart: always
    networks:
      - frontend
 
  wordpress:
    image: wordpress:6.6.1-fpm-alpine
    restart: always
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wp-content:/var/www/html/wp-content
    networks:
      - backend
      - frontend
 
volumes:
  db_data:
  wp-content:

networks:
  frontend:
  backend: