version: "3.8"
services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: pwdExample #TODO SECRET DOCKER
    restart: always
    networks:
      - backend
    volumes:
      - mariadb:/data

  wordpress:
    image: wordpress
    restart: always
    networks:
      - frontend
      - backend
    depends_on: 
      - db
    environment:
      WORDPRESS_DB_HOST: dbExample #TODO SECRET DOCKER
      WORDPRESS_DB_USER: exampleUser #TODO SECRET DOCKER
      WORDPRESS_DB_PASSWORD: examplePassword #TODO SECRET DOCKER
      WORDPRESS_DB_NAME: exampleDB #TODO SECRET DOCKER
    volumes:
      - wordpress:/var/www/html
  
  nginx:
    image: nginx
    ports:
    - "80:80"
    networks:
      - frontend
    volumes:
      - wordpress:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/fastcgi-php.conf

networks:
  frontend:
  backend:

volumes:
  wordpress:
  mariadb:
