version: '3.8'

services:
  db:
    image: mariadb:11.2
    volumes:
      - db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - backend
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: example

  wordpress:
    image: wordpress:6.6.1-fpm-alpine
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html
      
    networks:
      - frontend
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress

  nginx:
    image: nginx:1.27.1-alpine3.20
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - wordpress
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db_data:
