version: '3.8' #https://docs.docker.com/reference/compose-file/deploy/
 
services:
  db:
    image: mariadb:11.2
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password_here
    deploy:
      replicas: 1
 
  wordpress:
    image: wordpress
    depends_on:
      - db
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - frontend
      - backend
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password_here
      WORDPRESS_DB_NAME: wordpress
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - node.role == worker
 
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
    deploy:
      replicas: 2
 
networks:
  frontend:
    driver: overlay
    attachable: true
  backend:
    driver: overlay
    attachable: true
 
volumes:
  db_data:
  wordpress_data: