version: '3.8' #https://docs.docker.com/reference/compose-file/deploy/

services:
  db:
    image: mariadb:11.2
    volumes:
      - db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - backend
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/DB_ROOT_PWD
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: /run/secrets/DB_PWD
    deploy:
      mode: replicated
      replicas: 1
    secrets:
      - DB_PWD
      - DB_ROOT_PWD

  wordpress:
    image: wordpress:6.6.1-fpm-alpine
    depends_on:
      - db
    volumes:
      - wordpress_data:/var/www/html:nocopy
    networks:
      - frontend
    environment:
      WORDPRESS_DB_HOST: 172.26.0.33:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/DB_PWD
      WORDPRESS_DB_NAME: wordpress
    deploy:
      mode: replicated
      replicas: 1
    secrets:
      - DB_PWD
      - DB_ROOT_PWD
      - WP_PWD

  nginx:
    image: nginx:1.27.1-alpine3.20
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - wordpress
    networks:
      - frontend
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=172.26.1.5,nolock,soft,rw"
      device: ":/var/nfs_share/srv13"
  db_data:
secrets:
  DB_PWD:
    file: ./db_pwd.txt
  DB_ROOT_PWD:
    file: ./db_root_pwd.txt
  WP_PWD:
    file: ./wp_pwd.txt
