version: '3.8' #https://docs.docker.com/reference/compose-file/deploy/
 
services:
  db:
    image: mariadb:11.2
    volumes:
      - db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - backend
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password_here
    deploy:
      mode: replicated
      replicas: 1

  wordpress:
    image: wordpress:6.6.1-fpm-alpine
    depends_on:
      - db
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - frontend
      #- backend
    environment:
      WORDPRESS_DB_HOST: 172.26.0.33
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password_here
      WORDPRESS_DB_NAME: wordpress
    deploy:
      mode: replicated
      replicas: 3

  nginx:
    image: nginx:1.27.1-alpine3.20
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
      - /home/ubuntu/347-docker-swarm-wordpress/project/swarm/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
    networks:
      - frontend
      - backend
    deploy:
      mode: replicated
      replicas: 2
networks:
  frontend:
    driver: overlay
  backend:
volumes:
  wordpress_data:
  db_data: